class HtmlColors:
  def __init__(self):
    self.index = -1
    self.colors = HTML_COLORS
  
  def get_color(self):
    if self.index + 1 < len(self.colors):
      self.index += 1
    else:
      self.index = 0
    return self.colors[self.index]

HTML_COLORS = [
#	'AliceBlue',
#	'AntiqueWhite',
#	'Aqua',
	'Aquamarine',
#	'Azure',
#	'Beige',
#	'Bisque',
#	'Black',
#	'BlanchedAlmond',
	'Blue',
#	'BlueViolet',
#	'Brown',
#	'BurlyWood',
	'CadetBlue',
#	'Chartreuse',
#	'Chocolate',
	'Coral',
	'CornflowerBlue',
#	'Cornsilk',
#	'Crimson',
#	'Cyan',
#	'DarkBlue',
	'DarkCyan',
#	'DarkGoldenRod',
#	'DarkGray',
#	'DarkGrey',
	'DarkGreen',
#	'DarkKhaki',
	'DarkMagenta',
#	'DarkOliveGreen',
	'DarkOrange',
#	'DarkOrchid',
	'DarkRed',
	'DarkSalmon',
	'DarkSeaGreen',
	'DarkSlateBlue',
#	'DarkSlateGray',
#	'DarkSlateGrey',
	'DarkTurquoise',
	'DarkViolet',
	'DeepPink',
	'DeepSkyBlue',
#	'DimGray',
#	'DimGrey',
#	'DodgerBlue',
	'FireBrick',
#	'FloralWhite',
	'ForestGreen',
	'Fuchsia',
#	'Gainsboro',
#	'GhostWhite',
	'Gold',
#	'GoldenRod',
#	'Gray',
#	'Grey',
#	'Green',
	'GreenYellow',
# 'HoneyDew',
	'HotPink',
	'IndianRed',
#	'Indigo',
#	'Ivory',
#	'Khaki',
#	'Lavender',
#	'LavenderBlush',
#	'LawnGreen',
#	'LemonChiffon',
	'LightBlue',
	'LightCoral',
#	'LightCyan',
#	'LightGoldenRodYellow',
#	'LightGray',
#	'LightGrey',
	'LightGreen',
	'LightPink',
	'LightSalmon',
	'LightSeaGreen',
	'LightSkyBlue',
	'LightSlateGray',
	'LightSlateGrey',
	'LightSteelBlue',
#	'LightYellow',
#	'Lime',
	'LimeGreen',
#	'Linen',
	'Magenta',
	'Maroon',
	'MediumAquaMarine',
	'MediumBlue',
	'MediumOrchid',
	'MediumPurple',
	'MediumSeaGreen',
	'MediumSlateBlue',
	'MediumSpringGreen',
	'MediumTurquoise',
	'MediumVioletRed',
	'MidnightBlue',
	'MintCream',
	'MistyRose',
	'Moccasin',
	'NavajoWhite',
	'Navy',
	'OldLace',
	'Olive',
	'OliveDrab',
	'Orange',
	'OrangeRed',
	'Orchid',
	'PaleGoldenRod',
	'PaleGreen',
	'PaleTurquoise',
	'PaleVioletRed',
	'PapayaWhip',
	'PeachPuff',
	'Peru',
	'Pink',
	'Plum',
	'PowderBlue',
	'Purple',
	'RebeccaPurple',
	'Red',
	'RosyBrown',
	'RoyalBlue',
	'SaddleBrown',
	'Salmon',
	'SandyBrown',
	'SeaGreen',
	'SeaShell',
	'Sienna',
	'Silver',
	'SkyBlue',
	'SlateBlue',
	'SlateGray',
	'SlateGrey',
	'Snow',
	'SpringGreen',
	'SteelBlue',
	'Tan',
	'Teal',
	'Thistle',
	'Tomato',
	'Turquoise',
	'Violet',
	'Wheat',
	'White',
	'WhiteSmoke',
	'Yellow',
	'YellowGreen'
]